-- Step 1: Create Database and Generate Data
CREATE DATABASE IF NOT EXISTS INVENTORY_DB;
USE DATABASE INVENTORY_DB;
CREATE SCHEMA IF NOT EXISTS PUBLIC;

CREATE OR REPLACE TABLE RAW_INVENTORY_DATA AS
SELECT
    SEQ4() + 1 AS PRODUCT_ID,
    SNOWFLAKE.CORTEX.COMPLETE('llama3-70b', 'Return ONLY a short retail product name. ID: ' || (SEQ4()+1)) AS PRODUCT_NAME,
    UNIFORM(10, 500, RANDOM()) AS CURRENT_STOCK,
    UNIFORM(1, 100, RANDOM()) AS DAILY_SALES_AVG,
    UNIFORM(3, 30,  RANDOM()) AS LEAD_TIME_DAYS,
    SNOWFLAKE.CORTEX.COMPLETE('llama3-70b', 'Write 1 sentence about a shipping delay with a day count.') AS STATUS_NOTES
FROM TABLE(GENERATOR(ROWCOUNT => 100));