-- Step 2: AI Risk Classification
CREATE OR REPLACE TABLE ENRICHED_INVENTORY AS
SELECT
    r.*,
    ROUND(DAILY_SALES_AVG * LEAD_TIME_DAYS * 1.5) AS REORDER_POINT,
    SNOWFLAKE.CORTEX.SENTIMENT(STATUS_NOTES) AS SUPPLY_RISK_SCORE,
    SNOWFLAKE.CORTEX.EXTRACT_ANSWER(STATUS_NOTES, 'How many days is the delay?') AS EXTRACTED_DELAY,
    CASE
        WHEN CURRENT_STOCK < ROUND(DAILY_SALES_AVG * LEAD_TIME_DAYS * 1.5) THEN 'REORDER NOW'
        ELSE 'OK'
    END AS REORDER_STATUS
FROM RAW_INVENTORY_DATA r;