-- Step 3: Scaling with Dynamic Tables
CREATE OR REPLACE DYNAMIC TABLE REORDER_ALERTS
    TARGET_LAG = '1 minute'
    WAREHOUSE  = COMPUTE_WH
AS
SELECT * FROM ENRICHED_INVENTORY WHERE REORDER_STATUS != 'OK';