-- Step 4: Snowflake Horizon Governance
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS PROCUREMENT_ROLE;

CREATE OR REPLACE MASKING POLICY mask_pii AS (val STRING)
RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('PROCUREMENT_ROLE', 'ACCOUNTADMIN') THEN val
    ELSE '***MASKED***'
  END;

ALTER TABLE ENRICHED_INVENTORY MODIFY COLUMN STATUS_NOTES SET MASKING POLICY mask_pii;